import Head from 'next/head';
import logo from '../public/logo.png'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import { useState } from 'react';
import {AiFillTwitterCircle, AiFillLinkedin} from 'react-icons/ai'
import Image from 'next/image'
import emma from '../public/emma.jpeg'
import emma2 from '../public/emma2.png'
import design from '../public/design.jpg'
import write from '../public/write.png'
import code from '../public/code.png'


export default function Home() {

const [darkMode, setDarkMode] = useState(false)

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Emmanuel Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-gray-200'>
         
      
        <section className='bg-white px-10 dark:bg-gray-900'>
          <nav className='py-10 mb-12 flex justify-between'>
            <div className='relative w-70 h-90 '>
            {/* <Image 
            src={logo} 
            layout='fill' 
            objectFit='cover' 
            className='rounded-xl'
            /> */}
             <h1 className='text-xl dark:text-gray-300 font-burtons'>King Emma Dev</h1>
            </div>
             
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)} className='cursor-pointer'></BsFillMoonStarsFill>
              </li>
              <li><a className='text-white rounded-lg ml-10 px-4 py-2 bg-cyan-500 bg-gradient-to-r from-cyan-500 to-teal-500' href='https://drive.google.com/file/d/16yG10m6IPSJpMteOdJZscwcWPhrmo7Y6/view?usp=sharing' target='_blank'>Resume</a></li>
            </ul>
          </nav>
       

        <div className='text-center p-10'>
          <h2 className='text-5xl font-medium py-2 text-teal-500 md:text-6xl'>Emmanuel Mawulolo Tagbor</h2>
          <h3 className='text-xl py-5 md:text-3xl'>Senior Frontend Developer</h3>
          <p className='text-md py-5 leading-8 text-gray-700 md:text-xl max-w-lg mx-auto dark:text-gray-400'>
            With over 7 years of experience as a Frontend Web Developer, I am Passionate about building beautiful, functional and accessible designs and solving challenging problems using clean code! 

          </p>
        </div>

        <div className='relative bg-gradient-to-b from-teal-600 rounded-full mx-auto w-80 h-80 md:h-102 md:w-102'>
          <Image src={emma2} layout='fill' objectFit='cover'/>
        </div>
        
        <div className='flex justify-center gap-20 text-5xl text-gray-600 mt-10 dark:text-gray-300' >
          <a href='https://twitter.com/KingEmmaDev' target='_blank'>
          <AiFillTwitterCircle/>
          </a>
          <a href='https://www.linkedin.com/in/emmanuel-tagbor-656258112/' target='_blank'>
           <AiFillLinkedin />
          </a>
        </div>

        </section>

        <section>
          <div className='text-center my-10'>
            <h3 className='text-3xl py-1'>What I do!</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200 max-w-lg mx-auto'>
            I build aesthetic websites, teach Web development and code solutions to problems around me and from clients!  
            </p>

            <h4 className='py-2 text-teal-800 font-medium dark:text-teal-400'>Tech Stack</h4>
                <p className='py-1 text-gray-800 dark:text-gray-300'>HTML, CSS, JS</p>
                <p className='py-1 text-gray-800 dark:text-gray-300'>ReactJS</p>
                <p className='py-1 text-gray-800 dark:text-gray-300'>NextJS</p>
                <p className='py-1 text-gray-800 dark:text-gray-300'>Material UI / TailwindCSS</p>
          </div>

            <div className='lg:flex gap-10'>
              <div className='text-center shadow-xl p-10 rounded-xl my-10'>
                <Image className='mx-auto rounded-xl' src={design} width={200} height={200}/>
                <h3 className='text-lg font-medium pt-3 pb-2 '>Beautiful Web Applications</h3>
                <p className='py-1 text-gray-800 max-w-lg mx-auto dark:text-teal-600'>I combine frontend development skills with experience in HTML, CSS, JS, Bootstrap, Material UI, TailwindCSS, Express and Node.js to build responsive and accessible web applications that are modern and elegant!</p>
              </div>

              <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                <Image className='mx-auto rounded-xl' src={write} width={200} height={200}/>
                <h3 className='text-lg font-medium pt-3 pb-2 '>Technical Writing</h3>
                <p className='py-1 text-gray-800 max-w-lg mx-auto dark:text-teal-600'>One of my innate passions has always been writing! I seek to transform complex topics or procedures into simple and easy to understand documentation. I also have experience teaching Web development!</p>
              </div>

              <div className='text-center shadow-lg p-10 rounded-xl my-10'>
                <Image className='mx-auto rounded-xl' src={code} width={200} height={200}/>
                <h3 className='text-lg font-medium pt-3 pb-2 '>Software Development</h3>
                <p className='py-1 text-gray-800 max-w-lg mx-auto dark:text-teal-600'>Following design patterns, Test Driven Development, Performant algorithms and many other strategic best practices, I develop software solutions for any of your needs!</p>
              </div>
            </div>

        </section>


        {/* <section>
                <div>
                  <h3 className='text-3xl py-1'>Portfolio</h3>
                  <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
            I build aesthetic websites, teach Web development and code solutions to problems around me and from clients!  
            </p>
                </div>
              </section> */}

    </main>

    </div>
   
  )
}
